package types;

public enum AccessoryType {
    SHEET_MUSIC,
    GENERAL,
    STRING_ACCESSORIES,
    BRASS_ACCESSORIES,
    WOODWIND_ACCESSORIES,
    PERCUSSION_ACCESSORIES,
    KEYBOARD_ACCESSORIES,

}
